<?php

use App\Models\User;
use Spark\Features;

return [

    /*
    |--------------------------------------------------------------------------
    | Spark Path
    |--------------------------------------------------------------------------
    |
    | This configuration option determines the URI at which the Spark billing
    | portal is available. You are free to change this URI to a value that
    | you prefer. You shall link to this location from your application.
    |
    */

    'path' => 'billing',

    /*
    |--------------------------------------------------------------------------
    | Spark Middleware
    |--------------------------------------------------------------------------
    |
    | These are the middleware that requests to the Spark billing portal must
    | pass through before being accepted. Typically, the default list that
    | is defined below should be suitable for most Laravel applications.
    |
    */

    'middleware' => ['web', 'auth'],

    /*
    |--------------------------------------------------------------------------
    | Branding
    |--------------------------------------------------------------------------
    |
    | These configuration values allow you to customize the branding of the
    | billing portal, including the primary color and the logo that will
    | be displayed within the billing portal. This logo value must be
    | the absolute path to an SVG logo within the local filesystem.
    |
    */

    // 'brand' =>  [
    //     'logo' => realpath(__DIR__.'/../public/svg/billing-logo.svg'),
    //     'color' => 'bg-gray-800',
    // ],

    /*
    |--------------------------------------------------------------------------
    | Proration Behavior
    |--------------------------------------------------------------------------
    |
    | This value determines if charges are prorated when making adjustments
    | to a plan such as incrementing or decrementing the quantity of the
    | plan. This also determines proration behavior if changing plans.
    |
    */

    'prorates' => true,

    /*
    |--------------------------------------------------------------------------
    | Spark Date Format
    |--------------------------------------------------------------------------
    |
    | This date format will be utilized by Spark to format dates in various
    | locations within the billing portal, such as while showing invoice
    | dates. You should customize the format based on your own locale.
    |
    */

    'date_format' => 'F j, Y',

    /*
    |--------------------------------------------------------------------------
    | Features
    |--------------------------------------------------------------------------
    |
    | Some of Spark's features are optional. You may disable the features by
    | removing them from this array. By removing features from this array
    | you can customize your Spark experience for your own application.
    |
    */

    'features' => [
        // Features::billingAddressCollection(['required' => true]),
        // Features::mustAcceptTerms(),
        // Features::euVatCollection(['home-country' => 'BE']),
        // Features::receiptEmails(['custom-addresses' => true]),
        Features::paymentNotificationEmails(),
    ],

    /*
    |--------------------------------------------------------------------------
    | Receipt Configuration
    |--------------------------------------------------------------------------
    |
    | The following configuration options allow you to configure the data that
    | appears in PDF receipts generated by Spark. Typically, this data will
    | include a company name as well as your company contact information.
    |
    */

    'receipt_data' => [
        'vendor' => 'Aaiga Startups',
        'product' => 'Airproxy',
        'street' => '1 Collins St',
        'location' => 'Melbourne, AU',
        'phone' => '041-214-4625',
    ],

    /*
    |--------------------------------------------------------------------------
    | Spark Billable
    |--------------------------------------------------------------------------
    |
    | Below you may define billable entities supported by your Spark driven
    | application. The Stripe edition of Spark currently only supports a
    | single billable model entity (team, user, etc.) per application.
    |
    | In addition to defining your billable entity, you may also define its
    | plans and the plan's features, including a short description of it
    | as well as a "bullet point" listing of its distinctive features.
    |
    */

    'billables' => [

        'user' => [
            'model' => User::class,

            'trial_days' => 5,

            'default_interval' => 'monthly',

            'plans' => [
                [
                    'name' => 'Hobby',
                    'short_description' => 'The essentials to get up and running immediately with Airtable.',
                    'monthly_id' => 'price_1MnwxqFbI9pBujiNVv5vIZVJ',
                    'yearly_id' => 'price_1MnwxqFbI9pBujiNv8hpW7n1',
                    'yearly_incentive' => 'Save 17%',
                    'features' => [
                        'Unlimited bases',
                        'Unlimited tables',
                        'Up to 2.5k unique users',
                        'Up to 25k requests / month',
                    ],
                    'options' => [
                        'max_monthly_unique_users' => 2_500,
                        'max_monthly_requests' => 25_000,
                        'custom_ttls' => true,
                        'api_protection' => true,
                        'cdn' => true,
                    ],
                ],
                [
                    'name' => 'Team',
                    'short_description' => 'A plan that scales with your rapidly growing business.',
                    'monthly_id' => 'price_1MnwyQFbI9pBujiNilmd6sFs',
                    'yearly_id' => 'price_1MnwyQFbI9pBujiN8QUWbKtx',
                    'yearly_incentive' => 'Save 17%',
                    'features' => [
                        'Unlimited bases',
                        'Unlimited tables',
                        "Up to 7.5k unique users",
                        "Up to 1M requests / month",
                        "Custom TTLs",
                        "TypeScript definition generation",
                        "API protection",
                        "Image CDN",
                    ],
                    'options' => [
                        'max_monthly_unique_users' => 7_500,
                        'max_monthly_requests' => 1_000_000,
                        'custom_ttls' => true,
                        'api_protection' => true,
                        'cdn' => true,
                    ],
                ],
                [
                    'name' => 'Business',
                    'short_description' => 'Dedicated support and infrastructure for your company.',
                    'monthly_id' => 'price_1MnwylFbI9pBujiN6try6JyO',
                    'yearly_id' => 'price_1MnwylFbI9pBujiNvOuDAQda',
                    'yearly_incentive' => 'Save 17%',
                    'features' => [
                        "Unlimited bases",
                        "Unlimited tables",
                        "Up to 40K unique users",
                        "Up to 100M requests / month",
                        "Custom TTLs",
                        "TypeScript definition generation",
                        "API protection",
                        "Image CDN",
                    ],
                    'options' => [
                        'max_monthly_unique_users' => 40_000,
                        'max_monthly_requests' => 100_000_000,
                        'custom_ttls' => true,
                        'api_protection' => true,
                        'cdn' => true,
                    ],
                ],
            ],
        ],
    ],
];
